---
# tasks file for kube-worker-setup
         - name: "Installling docker software"
           package:
             name: "docker"
             state: present
         - name: "enable the service of docker"
           service:
             name: docker
             enabled: yes
             state: started
         - name: "setup the yum repository"
           yum_repository:
             name: "kubernetesrepo"
             description: "kubernetes repo to install kubectl,kubelet,kubeadm"
             baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
             gpgcheck: yes
             repo_gpgcheck: yes
             enabled: yes
             gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
                     https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         - name: "installing kubectl,kubeadm,kubelet"
           command: yum install -y kubelet kubectl kubeadm
         - name: "kubelet service enabled"
           service:
             name: kubelet
             enabled: yes
             state: started
         - name: "checking Cgroup driver"
           shell: docker info | grep -i cgroup
           register: x
         - debug:
                 var: x
         - name: "changing driver to systemd"
           copy:
              src: "daemon.json"
              dest: "/etc/docker/daemon.json"
         - name: "restarting docker"
           service:
              name: docker
              state: restarted
         - name: "checking Cgroup driver"
           shell: docker info | grep -i systemd
           register: y
         - debug:
                 var: y
         - name: "installing iproute-tc"
           package:
              name: iproute-tc
              state: present
         - name: "enabling bridging"
           copy:
                content: |
                      net.bridge.bridge-nf-call-ip6tables = 1
                      net.bridge.bridge-nf-call-iptables = 1
                dest: "/etc/sysctl.d/k8s.conf"
         - name: "running sysctl"
           command: "sysctl --system"

         - name: "clearing caches to increase the ram"
           shell: echo 3 > /proc/sys/vm/drop_caches
         - name: "getting join file"
           copy:
                   src: "/ans_kube_cluster/join.sh/{{groups['kube-master'][0]}}/join.sh"
                   dest: "{{location_join}}/join.sh"
                   mode: "u+rwx"
         - name: "running join file"
           shell: ./join.sh
           register: join_output

